// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    // javaSidebar: [{ type: 'autogenerated', dirName: 'Java' }],
    // pythonSidebar: [{ type: 'autogenerated', dirName: 'Python' }],
    pythonSidebar: [
        {
            type: 'category',
            label: 'Python 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/python'
                }
            ],
        }
    ],
    javaSidebar: [
        {
            type: 'category',
            label: 'Java 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/java'
                }
            ],
        }
    ],
    cppSidebar: [
        {
            type: 'category',
            label: 'C++ 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/cpp'
                }
            ],
        }
    ],
    javascriptSidebar: [
        {
            type: 'category',
            label: 'JavaScript 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/javascript'
                }
            ],
        }
    ],
    kubernetesSidebar: [
        {
            type: 'category',
            label: 'Kubernetes 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/kubernetes'
                }
            ],
        }
    ],
    springSidebar: [
        {
            type: 'category',
            label: 'Spring 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/spring'
                }
            ],
        }
    ],


    goSidebar: [
        {
            type: 'category',
            label: 'Go 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/go'
                }
            ],
        }
    ],

    redisSidebar: [
        {
            type: 'category',
            label: 'Redis 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/redis'
                }
            ],
        }
    ],
    swiftSidebar: [
        {
            type: 'category',
            label: 'Swift 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/swift'
                }
            ],
        }
    ],
    sqlSidebar: [
        {
            type: 'category',
            label: 'SQL 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/sql'
                }
            ],
        }
    ],
    cSidebar: [
        {
            type: 'category',
            label: 'C 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/c'
                }
            ],
        }
    ],
    csharpSidebar: [
        {
            type: 'category',
            label: 'C# 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/csharp'
                }
            ],
        }
    ],
    cssSidebar: [
        {
            type: 'category',
            label: 'CSS 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'web/css'
                }
            ],
        }
    ],
    phpSidebar: [
        {
            type: 'category',
            label: 'PHP 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/php'
                }
            ],
        }
    ],
    typescriptSidebar: [
        {
            type: 'category',
            label: 'TypeScript 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language/typescript'
                }
            ],
        }
    ],
    elasticsearchSidebar: [
        {
            type: 'category',
            label: 'Elasticsearch 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/elasticsearch'
                }
            ],
        }
    ],
    dockerSidebar: [
        {
            type: 'category',
            label: 'Docker 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/docker'
                }
            ],
        }
    ],
    kafkaSidebar: [
        {
            type: 'category',
            label: 'Kafka 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/kafka'
                }
            ],
        }
    ],
    gitSidebar: [
        {
            type: 'category',
            label: 'Git 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/git'
                }
            ],
        }
    ],

    jenkinsSidebar: [
        {
            type: 'category',
            label: 'Jenkins 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'devops/jenkins'
                }
            ],
        }
    ],
    mysqlSidebar: [
        {
            type: 'category',
            label: 'MySQL 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/mysql'
                }
            ],
        }
    ],
    postgresqlSidebar: [
        {
            type: 'category',
            label: 'PostgreSQL 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'database/postgresql'
                }
            ],
        }
    ],
    nacosSidebar: [
        {
            type: 'category',
            label: 'Nacos 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/nacos'
                }
            ],
        }
    ],
    nginxSidebar: [
        {
            type: 'category',
            label: 'Nginx 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/nginx'
                }
            ],
        }
    ],
    algorithmSidebar: [
        {
            type: 'category',
            label: '数据结构与算法',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fundamental/algorithm'
                }
            ],
        }
    ],
    rocketmqSidebar: [
        {
            type: 'category',
            label: 'RocketMQ 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/rocketmq'
                }
            ],
        }
    ],
    sentinelSidebar: [
        {
            type: 'category',
            label: 'Sentinel 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/sentinel'
                }
            ],
        }
    ],
    seataSidebar: [
        {
            type: 'category',
            label: 'Seata 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'middleware/seata'
                }
            ],
        }
    ],
    networkSidebar: [
        {
            type: 'category',
            label: '计算机网络',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fundamental/network'
                }
            ],
        }
    ],
    centosSidebar: [
        {
            type: 'category',
            label: 'CentOS 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'os/centos'
                }
            ],
        }
    ],
    ubuntuSidebar: [
        {
            type: 'category',
            label: 'Ubuntu 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'os/ubuntu'
                }
            ],
        }
    ],
    debianSidebar: [
        {
            type: 'category',
            label: 'Debian 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'os/debian'
                }
            ],
        }
    ],
    interviewSidebar: [
        {
            type: 'category',
            label: '八股面试宝典',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'fundamental/interview'
                }
            ],
        }
    ],
    springcloud_alibabaSidebar: [
        {
            type: 'category',
            label: 'Spring Cloud Alibaba 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'framework/springcloud_alibaba'
                }
            ],
        }
    ],
    databaseSidebar: [
        {
            type: 'category',
            label: '数据库与信息系统',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/database'}
            ],
        }
    ],
    eurekaSidebar: [
        {
            type: 'category',
            label: 'Eureka 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'middleware/eureka'}
            ],
        }
    ],
    htmlSidebar: [
        {
            type: 'category',
            label: 'HTML 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'web/html'}
            ],
        }
    ],
    arduinoSidebar: [
        {
            type: 'category',
            label: 'Arduino 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'iot/arduino'}
            ],
        }
    ],
    stm32Sidebar: [
        {
            type: 'category',
            label: 'STM32 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'iot/stm32'}
            ],
        }
    ],
    iot51Sidebar: [
        {
            type: 'category',
            label: '51 单片机教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'iot/51'}
            ],
        }
    ],
    osSidebar: [
        {
            type: 'category',
            label: '操作系统',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/os'}
            ],
        }
    ],
    djangoSidebar: [
        {
            type: 'category',
            label: 'Django 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/django'}
            ],
        }
    ],
    ginSidebar: [
        {
            type: 'category',
            label: 'Gin 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/gin'}
            ],
        }
    ],
    rabbitmqSidebar: [
        {
            type: 'category',
            label: 'RabbitMQ 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'middleware/rabbitmq'}
            ],
        }
    ],
    zookeeperSidebar: [
        {
            type: 'category',
            label: 'ZooKeeper 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'middleware/zookeeper'}
            ],
        }
    ],
    wechatminiprogramSidebar: [
        {
            type: 'category',
            label: '微信小程序开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/wechatminiprogram'}
            ],
        }
    ],
    android_javaSidebar: [
        {
            type: 'category',
            label: 'Android (Java) 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/android_java'}
            ],
        }
    ],
    pandasSidebar: [
        {
            type: 'category',
            label: 'Pandas 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/pandas'}
            ],
        }
    ],
    android_kotlinSidebar: [
        {
            type: 'category',
            label: 'Android (Kotlin) 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/android_kotlin'}
            ],
        }
    ],
    nextjsSidebar: [
        {
            type: 'category',
            label: 'Next.js 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/nextjs'}
            ],
        }
    ],
    reactSidebar: [
        {
            type: 'category',
            label: 'React 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/react'}
            ],
        }
    ],
    pytorchSidebar: [
        {
            type: 'category',
            label: 'PyTorch 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'ai/pytorch'}
            ],
        }
    ],
    tensorflowSidebar: [
        {
            type: 'category',
            label: 'Tensorflow 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'ai/tensorflow'}
            ],
        }
    ],
    vueSidebar: [
        {
            type: 'category',
            label: 'Vue.js 开发教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'framework/vue'}
            ],
        }
    ],
    leanSidebar: [
        {
            type: 'category',
            label: '系统设计与验证 (Lean)',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/lean'}
            ],
        }
    ],
    cassandraSidebar: [
        {
            type: 'category',
            label: 'Cassandra 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'database/cassandra'}
            ],
        }
    ],
    hbaseSidebar: [
        {
            type: 'category',
            label: 'HBase 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'database/hbase'}
            ],
        }
    ],
    hiveSidebar: [
        {
            type: 'category',
            label: 'Hive 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'database/hive'}
            ],
        }
    ],
    airflowSidebar: [
        {
            type: 'category',
            label: 'Airflow 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/airflow'}
            ],
        }
    ],
    drillSidebar: [
        {
            type: 'category',
            label: 'Drill 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/drill'}
            ],
        }
    ],
    hadoopSidebar: [
        {
            type: 'category',
            label: 'Hadoop 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/hadoop'}
            ],
        }
    ],
    rSidebar: [
        {
            type: 'category',
            label: 'R 语言教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/r'}
            ],
        }
    ],
    sparkSidebar: [
        {
            type: 'category',
            label: 'Spark 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'data/spark'}
            ],
        }
    ],
    alloySidebar: [
        {
            type: 'category',
            label: 'Alloy 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/alloy'}
            ],
        }
    ],
    grafanaSidebar: [
        {
            type: 'category',
            label: 'Grafana 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/grafana'}
            ],
        }
    ],
    lokiSidebar: [
        {
            type: 'category',
            label: 'Loki 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/loki'}
            ],
        }
    ],
    prometheusSidebar: [
        {
            type: 'category',
            label: 'Prometheus 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/prometheus'}
            ],
        }
    ],
    jaegerSidebar: [
        {
            type: 'category',
            label: 'Jaeger 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/jaeger'}
            ],
        }
    ],
    opentelemetrySidebar: [
        {
            type: 'category',
            label: 'OpenTelemetry 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/opentelemetry'}
            ],
        }
    ],
    skywalkingSidebar: [
        {
            type: 'category',
            label: 'SkyWalking 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/skywalking'}
            ],
        }
    ],
    zipkinSidebar: [
        {
            type: 'category',
            label: 'Zipkin 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'observability/zipkin'}
            ],
        }
    ],
    prismSidebar: [
        {
            type: 'category',
            label: 'Prism 教程',
            link: {
                type: 'generated-index',
            },
            collapsible: false,
            collapsed: false,
            items: [
                {type: 'autogenerated', dirName: 'fundamental/prism'}
            ],
        }
    ],


};

export default sidebars;
